import { CONFIG } from "../config";


export const ClaimConfig:any = {
  rewardsServer: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'https://rewards.decentraland.zone' : 'https://rewards.decentraland.org',
  campaign: {
      RatEscape: {
        campaign: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_ID_HERE' : 'PROD_CAMPAIGN_ID_HERE',
        campaignKeys: {
          level0: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE",
          level2: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE",
          level4: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE",
          level6: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE",
          level8: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE",
          level10: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE",
          level12: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE",
          level13: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE",
          levelcheeseshirt: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE", 
          levelbowl: CONFIG.CONFIG_CLAIM_TESTING_ENABLED ? 'TEST_CAMPAIGN_KEY_HERE' : "PROD_CAMPAIGN_KEY_HERE"
        }
      },
  }
}